networks:
  dst:
    name: dst-island
services:
  dst-server:
     container_name: dst-server-island
     image: tws101/docker-dst-server:island-latest
     restart: "on-failure:5"
     networks:
      - dst-island
     ports:
        - "11001-11004:11001-11004/udp"
        - "12546-12549:12546-12549/udp"
     volumes:
        - ${PATH_ON_HOST}:/data
     stop_grace_period: 6m
